### ISSUE TITLE
Unable to run the script , it's throwing error as System property "mbrola.base" is undefined.  Will not use MBROLA voices.

### ISSUE THREAD

**Issue by vidyasagarpogiri** [vinsguru/google-voice-search#1]
@vinsguru , please help me I'm getting this error 

System property "mbrola.base" is undefined.  Will not use MBROLA voices.
Jul 30, 2018 6:22:41 PM org.jboss.arquillian.drone.impl.DroneTestEnricher ensureInjectionPointPrepared
WARNING: Injection point DronePointImpl{droneClass=interface org.openqa.selenium.WebDriver, annotations=[@org.jboss.arquillian.drone.api.annotation.Drone()], lifecycle=CLASS} was not prepared yet. It will be prepared now, but it's recommended that all drones with class lifecycle are prepared in @BeforeClass by the DroneLifecycleManager!
FAILED CONFIGURATION: @BeforeMethod arquillianBeforeTest(public void com.testautomationguru.google.search.test.GoogleVoiceTest.googleVoiceSearchTest(java.lang.String) throws java.lang.InterruptedException)
org.jboss.arquillian.graphene.enricher.exception.PageObjectInitializationException: Can not instantiate Page Object 

Thank you .

**Comment by vinsguru** [comment]
Fixed. Works fine now. Included a demo as well
